export interface project {
    id: any,
    uuid: any,
    project_name: any,
    display_name: any,
    title: any,
    publisher_id: any,
    type_id: any,
    project_complexity: any,
    workflow: any,
    trim_size: any,
    isbn: any,
    digital_isbn: any,
    issn: any,
    issue: any,
    start_date: any,
    due_date: any,
    site_id: any,
    pdf_template_id: any,
    xml_template_id: any,
    xslt_template_id: any,
    xslt_id: any,
    template_color: any,
    coverimage_file_id: any,
    reference: any,
    image :any,
    reference_citation: any,
    reference_style: any,
    is_completed: any,
    is_split: any,
    is_active: any,
    is_deleted: any,
    created_on: any,
    created_by: any,
    modified_on: any,
    modified_by: any,
    deleted_on: any,
    deleted_by: any,
    site_name: any,
    publisher_name: any,
    publisher_uuid: any,
    project_type: any,
    projecttype_uuid: any,
    file_path: any,
    file_name: any,
    first_name: any,
    last_name: any,
    toggle :boolean
}



export const projectData:project[] = [
    {
        "id": "342",
        "uuid": "dac38e9f-bfdb-11ec-b908-002590e66074",
        "project_name": "new_1",
        "display_name": "New_1",
        "title": "new_1",
        "publisher_id": "10",
        "type_id": "1",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-04-01 00:00:00",
        "due_date": "2022-04-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "BOOKEND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-04-19 17:55:53",
        "created_by": "519",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "kealaxshan",
        "last_name": "s",
        "image" : null,
        "toggle": false
    },
    {
        "id": "341",
        "uuid": "3fd54b0e-bc87-11ec-b908-002590e66074",
        "project_name": "planeta_publishing",
        "display_name": "Planeta_Publishing",
        "title": "planeta_publishing",
        "publisher_id": "7",
        "type_id": "1",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-04-15 00:00:00",
        "due_date": "2022-07-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-04-15 12:12:41",
        "created_by": "489",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Poornima",
        "last_name": "H",
        "image" : null,
        "toggle": false
    },
    {
        "id": "340",
        "uuid": "54e206cd-af28-11ec-b908-002590e66074",
        "project_name": "NewBookA",
        "display_name": null,
        "title": "NewBookA",
        "publisher_id": "10",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "1",
        "xml_template_id": "12",
        "xslt_template_id": "2",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-29 11:50:29",
        "created_by": "161",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S",
        "image" : null,
        "toggle": false
    },
    {
        "id": "339",
        "uuid": "5794d86e-ae93-11ec-b908-002590e66074",
        "project_name": "Test-authoring",
        "display_name": null,
        "title": "Test-authoring",
        "publisher_id": "11",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "1",
        "xml_template_id": "12",
        "xslt_template_id": "2",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-28 18:03:59",
        "created_by": "272",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "DiacriTech",
        "publisher_uuid": "646fdb61-09e3-11ea-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Dinesh",
        "last_name": "Krishnan",
        "image" : null,
        "toggle": false
    },
    {
        "id": "338",
        "uuid": "424d85fe-9ea9-11ec-9acd-42010a800009",
        "project_name": "duplicate_dt-jsdesign",
        "display_name": "duplicate_dt-jsdesign",
        "title": "duplicate_dt-jsdesign",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "33",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 12:00:34",
        "created_by": "261",
        "modified_on": "2022-03-08 18:05:21",
        "modified_by": "188",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren",
        "image" : null,
        "toggle": false
    },
    {
        "id": "337",
        "uuid": "f25af83d-9ea8-11ec-9acd-42010a800009",
        "project_name": "Testproj",
        "display_name": "Testproj",
        "title": "Testproj",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 11:58:19",
        "created_by": "261",
        "modified_on": "2022-03-24 15:45:11",
        "modified_by": "272",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren",
        "image" : null,
        "toggle": false
    },
    {
        "id": "336",
        "uuid": "dae5b5c5-9ea8-11ec-9acd-42010a800009",
        "project_name": "Test_Proj",
        "display_name": "Test_Proj",
        "title": "Test_Proj",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 11:57:40",
        "created_by": "261",
        "modified_on": "2022-03-15 10:25:16",
        "modified_by": "272",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren",
        "image" : null,
        "toggle": false
    },
    {
        "id": "335",
        "uuid": "c696cbde-9ea8-11ec-9acd-42010a800009",
        "project_name": "Testing_Project",
        "display_name": "Testing_Project",
        "title": "Testing_Project",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 11:57:06",
        "created_by": "261",
        "modified_on": "2022-03-24 15:09:52",
        "modified_by": "272",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren",
        "image" : null,
        "toggle": false
    },
    {
        "id": "333",
        "uuid": "6608e5ca-9c6c-11ec-9acd-42010a800009",
        "project_name": "EquationReorder-JSDesign",
        "display_name": "EquationReorder-JSDesign",
        "title": "EquationReorder-JSDesign",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-05 15:39:52",
        "created_by": "386",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Bharani",
        "last_name": "M",
        "image" : null,
        "toggle": false
    },
    {
        "id": "332",
        "uuid": "683ea6a4-93c3-11ec-9acd-42010a800009",
        "project_name": "training_sample-22022022",
        "display_name": "Training_sample-22022022",
        "title": "training_sample-22022022",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "APA",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 15:10:01",
        "created_by": "1",
        "modified_on": "2022-03-02 18:26:31",
        "modified_by": "404",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Super",
        "last_name": "Admin",
        "image" : null,
        "toggle": false
    },
    {
        "id": "331",
        "uuid": "0a82e40d-93c1-11ec-9acd-42010a800009",
        "project_name": "training_sample_test22022",
        "display_name": "Training_sample_test22022",
        "title": "training_sample_test22022",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 14:53:05",
        "created_by": "1",
        "modified_on": "2022-03-02 18:09:39",
        "modified_by": "404",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Super",
        "last_name": "Admin",
        "image" : null,
        "toggle": false
    },
    {
        "id": "330",
        "uuid": "6b232956-93c0-11ec-9acd-42010a800009",
        "project_name": "training_sample_test22021",
        "display_name": "Training_sample_test22021",
        "title": "training_sample_test22021",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 14:48:38",
        "created_by": "1",
        "modified_on": "2022-03-02 18:18:14",
        "modified_by": "404",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Super",
        "last_name": "Admin",
        "image" : null,
        "toggle": false
    },
    {
        "id": "329",
        "uuid": "19cf1fe1-93be-11ec-9acd-42010a800009",
        "project_name": "Journal_copy",
        "display_name": "Journal_copy",
        "title": "Journal_copy",
        "publisher_id": "20",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-02-21 00:00:00",
        "due_date": "2023-02-28 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 14:32:02",
        "created_by": "161",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewPublisher",
        "publisher_uuid": "f4f68663-2a30-11eb-b771-42010a800009",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S",
        "image" : null,
        "toggle": false
    },
    {
        "id": "328",
        "uuid": "fe954780-93bd-11ec-9acd-42010a800009",
        "project_name": "Training_Sample_Test_20220222a",
        "display_name": "Training_Sample_Test_20220222a",
        "title": "Training_Sample_Test_20220222a",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-03-01 00:00:00",
        "due_date": "2023-03-10 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 14:31:17",
        "created_by": "161",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S",
        "image" : null,
        "toggle": false
    },
    {
        "id": "327",
        "uuid": "085ecc67-93b0-11ec-9acd-42010a800009",
        "project_name": "Training sample7 test files",
        "display_name": "Training sample7 test files",
        "title": "Training sample7 test files",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-03-01 00:00:00",
        "due_date": "2023-03-10 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 12:51:20",
        "created_by": "291",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Sabari",
        "last_name": "R",
        "image" : null,
        "toggle": false
    },
    {
        "id": "326",
        "uuid": "d88c0d17-93af-11ec-9acd-42010a800009",
        "project_name": "Training_Sample7 Test files",
        "display_name": "Training_Sample7 Test files",
        "title": "Training_Sample7 Test files",
        "publisher_id": "1",
        "type_id": "1",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-03-01 00:00:00",
        "due_date": "2023-03-10 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-22 12:50:00",
        "created_by": "291",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "CUPA",
        "publisher_uuid": "6f80842b-daa9-11e9-8f57-42010a800002",
        "project_type": "BOOK",
        "projecttype_uuid": "94cd3f32-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Sabari",
        "last_name": "R",
        "image" : null,
        "toggle": false
    },
    {
        "id": "325",
        "uuid": "c2c49b30-930c-11ec-9acd-42010a800009",
        "project_name": "Sample_Anandan",
        "display_name": "Sample_Anandan",
        "title": "Sample_Anandan",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-02-22 00:00:00",
        "due_date": "2022-04-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "Author",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-21 17:22:35",
        "created_by": "490",
        "modified_on": "2022-02-21 17:41:38",
        "modified_by": "490",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen",
        "image" : null,
        "toggle": false
    },
    {
        "id": "324",
        "uuid": "8850ed47-925e-11ec-9acd-42010a800009",
        "project_name": "journal",
        "display_name": "Journal",
        "title": "journal",
        "publisher_id": "20",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-02-21 00:00:00",
        "due_date": "2023-02-28 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "Author",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:35:25",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewPublisher",
        "publisher_uuid": "f4f68663-2a30-11eb-b771-42010a800009",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen",
        "image" : null,
        "toggle": false
    },
    {
        "id": "323",
        "uuid": "0dfbc6cb-925d-11ec-9acd-42010a800009",
        "project_name": "Journal sample",
        "display_name": null,
        "title": "Journal sample",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:24:50",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen",
        "image" : null,
        "toggle": false
    },
    {
        "id": "322",
        "uuid": "eff1bc86-925c-11ec-9acd-42010a800009",
        "project_name": "Journal sample",
        "display_name": null,
        "title": "Journal sample",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:24:00",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen",
        "image" : null,
        "toggle": false
    }
]