export const bookArr = [
    {
        "id": "345",
        "uuid": "58b99f26-e8a6-11ec-96ba-002590e66074",
        "project_name": "perl_test_for_journal",
        "display_name": "Perl_Test_For_Journal",
        "title": "perl_test_for_journal",
        "publisher_id": "11",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-06-02 00:00:00",
        "due_date": "2022-06-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "1",
        "xml_template_id": "14",
        "xslt_template_id": "41",
        "xslt_id": "17",
        "template_color": "",
        "coverimage_file_id": null,
        "reference": "BOOKEND",
        "reference_citation": "2",
        "reference_style": "CMS_Notes",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-06-10 15:46:09",
        "created_by": "416",
        "modified_on": "2022-06-10 15:47:31",
        "modified_by": "416",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "DiacriTech",
        "publisher_uuid": "646fdb61-09e3-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "SURYA",
        "last_name": "R"
    },
    {
        "id": "338",
        "uuid": "424d85fe-9ea9-11ec-9acd-42010a800009",
        "project_name": "duplicate_dt-jsdesign",
        "display_name": "Duplicate_dt-jsdesign",
        "title": "duplicate_dt-jsdesign",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "33",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 12:00:34",
        "created_by": "261",
        "modified_on": "2022-06-08 18:15:01",
        "modified_by": "272",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren"
    },
    {
        "id": "337",
        "uuid": "f25af83d-9ea8-11ec-9acd-42010a800009",
        "project_name": "Testproj",
        "display_name": "Testproj",
        "title": "Testproj",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "182",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-03-08 11:58:19",
        "created_by": "261",
        "modified_on": "2022-06-08 18:15:20",
        "modified_by": "272",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Prakash",
        "last_name": "Rajendren"
    },
    {
        "id": "325",
        "uuid": "c2c49b30-930c-11ec-9acd-42010a800009",
        "project_name": "Sample_Anandan",
        "display_name": "Sample_Anandan",
        "title": "Sample_Anandan",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2022-02-22 00:00:00",
        "due_date": "2022-04-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "Author",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-21 17:22:35",
        "created_by": "490",
        "modified_on": "2022-02-21 17:41:38",
        "modified_by": "490",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen"
    },
    {
        "id": "323",
        "uuid": "0dfbc6cb-925d-11ec-9acd-42010a800009",
        "project_name": "Journal sample",
        "display_name": null,
        "title": "Journal sample",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:24:50",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen"
    },
    {
        "id": "322",
        "uuid": "eff1bc86-925c-11ec-9acd-42010a800009",
        "project_name": "Journal sample",
        "display_name": null,
        "title": "Journal sample",
        "publisher_id": "7",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:24:00",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewCustomer",
        "publisher_uuid": "d4649387-eb44-11e9-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen"
    },
    {
        "id": "321",
        "uuid": "c590343f-925c-11ec-9acd-42010a800009",
        "project_name": "Journal sample",
        "display_name": null,
        "title": "Journal sample",
        "publisher_id": "20",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2022-02-20 20:22:49",
        "created_by": "490",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "NewPublisher",
        "publisher_uuid": "f4f68663-2a30-11eb-b771-42010a800009",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Anandan ",
        "last_name": "Bommen"
    },
    {
        "id": "227",
        "uuid": "83e2d3ba-1543-11ec-9ce3-42010a800009",
        "project_name": "Ref_test_140921",
        "display_name": "Ref_test_140921",
        "title": "Ref_test_140921",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-07-31 00:00:00",
        "due_date": "2021-09-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "72",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-09-14 15:37:06",
        "created_by": "415",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Raajthilak",
        "last_name": "Nagarajan"
    },
    {
        "id": "201",
        "uuid": "ba9816f0-fff0-11eb-9ce3-42010a800009",
        "project_name": "journal-article-meta",
        "display_name": null,
        "title": "journal-article-meta",
        "publisher_id": "11",
        "type_id": "2",
        "project_complexity": "MEDIUM",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": null,
        "due_date": null,
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-08-18 12:21:35",
        "created_by": "188",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "DiacriTech",
        "publisher_uuid": "646fdb61-09e3-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Nainar",
        "last_name": "Ravi"
    },
    {
        "id": "199",
        "uuid": "4f80f4eb-f695-11eb-91e5-42010a800009",
        "project_name": "tetsting06082021",
        "display_name": "tetsting06082021",
        "title": "tetsting06082021",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-07-31 00:00:00",
        "due_date": "2021-09-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "72",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-08-06 14:34:30",
        "created_by": "1",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Super",
        "last_name": "Admin"
    },
    {
        "id": "196",
        "uuid": "b261eda4-f372-11eb-91e5-42010a800009",
        "project_name": "SampleJournal_AMAStyle_for_FL",
        "display_name": "SampleJournal_AMAStyle_for_FL",
        "title": "SampleJournal_AMAStyle_for_FL",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-08-02 00:00:00",
        "due_date": "2021-09-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "AMA",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-08-02 14:49:10",
        "created_by": "161",
        "modified_on": "2021-08-02 14:50:40",
        "modified_by": "161",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    },
    {
        "id": "195",
        "uuid": "4ed76618-f1ca-11eb-91e5-42010a800009",
        "project_name": "SampleJournal_APAStyle_for_FL",
        "display_name": "SampleJournal_APAStyle_for_FL",
        "title": "SampleJournal_APAStyle_for_FL",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-07-31 00:00:00",
        "due_date": "2021-09-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "72",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "APA7ed",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-07-31 12:11:17",
        "created_by": "161",
        "modified_on": "2021-07-31 14:56:16",
        "modified_by": "165",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    },
    {
        "id": "194",
        "uuid": "42615cf1-f101-11eb-91e5-42010a800009",
        "project_name": "Test008",
        "display_name": "Test008",
        "title": "Test008",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-07-30 00:00:00",
        "due_date": "2021-08-10 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "BOOKEND",
        "reference_citation": "2",
        "reference_style": "APA",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-07-30 12:12:07",
        "created_by": "350",
        "modified_on": "2021-08-04 15:52:12",
        "modified_by": "350",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Ganapathy",
        "last_name": "Maheshwaran"
    },
    {
        "id": "193",
        "uuid": "a39fc357-f067-11eb-91e5-42010a800009",
        "project_name": "JSDOC_R",
        "display_name": "JSDOC_R",
        "title": "JSDOC_R",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-07-15 00:00:00",
        "due_date": "2021-08-15 00:00:00",
        "site_id": "1",
        "pdf_template_id": "72",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "APA",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-07-29 17:52:28",
        "created_by": "161",
        "modified_on": "2021-08-03 18:36:09",
        "modified_by": "161",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    },
    {
        "id": "192",
        "uuid": "bed13da7-eb85-11eb-91e5-42010a800009",
        "project_name": "duplicate indesign JSdesign",
        "display_name": "duplicate indesign JSdesign",
        "title": "duplicate indesign JSdesign",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "43",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-07-23 12:45:22",
        "created_by": "350",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Ganapathy",
        "last_name": "Maheshwaran"
    },
    {
        "id": "155",
        "uuid": "a6a2d8f2-b956-11eb-91e5-42010a800009",
        "project_name": "DT-JSDesign",
        "display_name": "DT-JSDesign",
        "title": "DT-JSDesign",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-05-20 00:00:00",
        "due_date": "2021-05-30 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "33",
        "xslt_template_id": "182",
        "xslt_id": "5",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": "APA",
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-05-20 16:02:17",
        "created_by": "161",
        "modified_on": "2022-03-22 17:47:01",
        "modified_by": "422",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    },
    {
        "id": "145",
        "uuid": "58e73b8b-7e70-11eb-9b18-42010a800009",
        "project_name": "Parsit Reference",
        "display_name": "Parsit Reference",
        "title": "Parsit Reference",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "LaTEX",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-03-10 00:00:00",
        "due_date": "2021-03-19 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-03-06 17:07:35",
        "created_by": "16",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Tamil",
        "last_name": "arasu"
    },
    {
        "id": "141",
        "uuid": "7e6dd652-7694-11eb-8809-42010a800009",
        "project_name": "Springer_Journal_STD_Test",
        "display_name": "Springer_Journal_STD_Test",
        "title": "Springer_Journal_STD_Test",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-02-24 00:00:00",
        "due_date": "2021-02-28 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "0",
        "xslt_template_id": "0",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-02-24 17:06:11",
        "created_by": "161",
        "modified_on": "2021-02-25 15:32:45",
        "modified_by": "161",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    },
    {
        "id": "134",
        "uuid": "282d3a04-6f80-11eb-8aba-42010a800009",
        "project_name": "referencemerge check",
        "display_name": "referencemerge check",
        "title": "referencemerge check",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-02-02 00:00:00",
        "due_date": "2021-02-25 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "43",
        "xslt_id": "0",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-02-15 16:52:58",
        "created_by": "16",
        "modified_on": null,
        "modified_by": null,
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Tamil",
        "last_name": "arasu"
    },
    {
        "id": "132",
        "uuid": "58442967-6529-11eb-a081-42010a800009",
        "project_name": "DT-JSDTC",
        "display_name": "DT-JSDTC",
        "title": "DT-JSDTC",
        "publisher_id": "10",
        "type_id": "2",
        "project_complexity": "SIMPLE",
        "workflow": "InDesign",
        "trim_size": null,
        "isbn": null,
        "digital_isbn": null,
        "issn": null,
        "issue": null,
        "start_date": "2021-02-02 00:00:00",
        "due_date": "2021-02-28 00:00:00",
        "site_id": "1",
        "pdf_template_id": "0",
        "xml_template_id": "7",
        "xslt_template_id": "43",
        "xslt_id": "5",
        "template_color": null,
        "coverimage_file_id": null,
        "reference": "CHAPTEREND",
        "reference_citation": "2",
        "reference_style": null,
        "is_completed": "0",
        "is_split": "0",
        "is_active": "1",
        "is_deleted": "0",
        "created_on": "2021-02-02 13:06:21",
        "created_by": "161",
        "modified_on": "2021-02-08 14:07:53",
        "modified_by": "161",
        "deleted_on": null,
        "deleted_by": null,
        "site_name": "API",
        "publisher_name": "Sample",
        "publisher_uuid": "334a57e8-047a-11ea-8f57-42010a800002",
        "project_type": "JOURNAL",
        "projecttype_uuid": "a1cfa97e-93e9-11e8-8cf9-309c2328295e",
        "file_path": null,
        "file_name": null,
        "first_name": "Balamurugan",
        "last_name": "S"
    }
]


export const chapterArr = [
    {
      "file_uuid": "75b4b15d-6d25-11ec-ac4f-42010a800009",
      "type": "chp",
      "chapter_name": "Block_III_Chap_10",
      "is_disable": true
    },
    {
      "file_uuid": "d1290ac9-6d44-11ec-ac4f-42010a800009",
      "type": "chp",
      "chapter_name": "CAT_Prelims",
      "is_disable": true
    }
  ]